"""add_proveedor_facturas_table

Revision ID: 002e344a1a64
Revises: 4edb9373065b
Create Date: 2026-06-12 11:59:40.437651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002e344a1a64'
down_revision = '4edb9373065b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor_facturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=200), nullable=False),
    sa.Column('orden_compra_url', sa.String(length=500), nullable=True),
    sa.Column('comprobante_compra_url', sa.String(length=500), nullable=True),
    sa.Column('banco_pago_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('plazo_dias', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('valor_neto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_cancelado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('retencion', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedor_facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedor_facturas_nombre_proveedor'), ['nombre_proveedor'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor_facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedor_facturas_nombre_proveedor'))

    op.drop_table('proveedor_facturas')
    # ### end Alembic commands ###
