"""Agregar modelos de requisicion a oficina

Revision ID: 09ec72562046
Revises: c7b40654ae9f
Create Date: 2026-04-06 15:35:09.425060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ec72562046'
down_revision = 'c7b40654ae9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requisiciones_oficina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bodeguero_id', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'COMPRADA', 'RECHAZADA', name='estado_req_oficina_enum'), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bodeguero_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_requisicion_oficina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisicion_id', sa.Integer(), nullable=False),
    sa.Column('material_texto', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['requisicion_id'], ['requisiciones_oficina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_requisicion_oficina')
    op.drop_table('requisiciones_oficina')
    # ### end Alembic commands ###
