"""tabla detalle de solicitud

Revision ID: 25bcbe573276
Revises: 847f5431f6ad
Create Date: 2026-02-07 08:44:25.594314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bcbe573276'
down_revision = '847f5431f6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_solicitud_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiales.id_material'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes_materiales.id_solicitud'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_solicitud_material')
    # ### end Alembic commands ###
