"""Permitir eliminar personal

Revision ID: 42089929ee1a
Revises: 97eed943f45b
Create Date: 2026-02-11 11:35:46.654557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42089929ee1a'
down_revision = '97eed943f45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proyectos_responsable_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'personal', ['responsable_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proyectos_responsable_id_fkey'), 'personal', ['responsable_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    # ### end Alembic commands ###
