"""Migracion a SubProyectos

Revision ID: 497dcdcf54ca
Revises: ad8f6ae3ab29
Create Date: 2026-06-18 15:31:58.011376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497dcdcf54ca'
down_revision = 'ad8f6ae3ab29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_proyectos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre_miniproyecto', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id_proyecto'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_proyecto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sub_proyectos', ['sub_proyecto_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sub_proyecto_id')

    op.drop_table('sub_proyectos')
    # ### end Alembic commands ###
