"""Limpiar modelo bancos

Revision ID: 4edb9373065b
Revises: ecafa381425c
Create Date: 2026-06-09 15:44:26.828918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4edb9373065b'
down_revision = 'ecafa381425c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.drop_column('ultima_sincronizacion')
        batch_op.drop_column('link_bancario_id')
        batch_op.drop_column('banco_externo_status')
        batch_op.drop_column('institucion_externa')
        batch_op.drop_column('cuenta_externa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta_externa_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('institucion_externa', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('banco_externo_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('link_bancario_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ultima_sincronizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
