"""add_activo_en_nomina_to_usuarios

Revision ID: 5b8e9f2a1c3d
Revises: 497dcdcf54ca
Create Date: 2026-09-29 10:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8e9f2a1c3d'
down_revision = '497dcdcf54ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo_en_nomina', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo_en_nomina')
    # ### end Alembic commands ###
