"""Cambio en Actas

Revision ID: 6932328d5094
Revises: b080a1b4f3e9
Create Date: 2026-02-18 14:31:26.854539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6932328d5094'
down_revision = 'b080a1b4f3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fecha_envio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('valor_consignado', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.alter_column('fecha_recepcion',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('numero_documento',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('abono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abono', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
        batch_op.alter_column('numero_documento',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('fecha_recepcion',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('valor_consignado')
        batch_op.drop_column('fecha_envio')
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
