"""cambios solicitud de material

Revision ID: 761ad2dfaf1f
Revises: 98913d983ec7
Create Date: 2026-03-25 15:14:09.839018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761ad2dfaf1f'
down_revision = '98913d983ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_solicitud_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_entregada', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('observacion_bodega', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('fecha_entrega_estimada', sa.Date(), nullable=True))
        batch_op.alter_column('id_material',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_solicitud_material', schema=None) as batch_op:
        batch_op.alter_column('id_material',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('fecha_entrega_estimada')
        batch_op.drop_column('observacion_bodega')
        batch_op.drop_column('cantidad_entregada')

    # ### end Alembic commands ###
