"""Inicial

Revision ID: 847f5431f6ad
Revises: 
Create Date: 2026-01-30 10:13:23.179542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847f5431f6ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('proyecto', sa.String(length=150), nullable=False),
    sa.Column('numero_cotizacion', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACEPTADA', 'RECHAZADA', name='estado_cotizacion_enum'), nullable=False),
    sa.Column('imagen_cotizacion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cotizacion')
    )
    op.create_table('materiales',
    sa.Column('id_material', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('Ingeniero', 'Trabajador', 'Bodeguero', 'Administrativo', 'Otra', name='rol_personal_enum'), nullable=False),
    sa.Column('rol_personalizado', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('costo_diario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contacto', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contacto')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('proyecto', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'FACTURADO', name='estado_factura_real_enum'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('anticipo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cotizacion_id')
    )
    op.create_table('historial_materiales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_proyecto_eliminado', sa.String(length=150), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('nombre_material', sa.String(length=100), nullable=False),
    sa.Column('unidad_material', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['materiales.id_material'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos',
    sa.Column('id_proyecto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('lugar', sa.String(length=150), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('EN_PROGRESO', 'FINALIZADO', 'PENDIENTE', 'ATRASADO', name='estado_proyecto_enum'), nullable=True),
    sa.Column('fecha_fin_real', sa.Date(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['personal.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_proyecto')
    )
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proyectos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_proyectos_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_proyectos_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_proyectos_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_proyectos_responsable_id'), ['responsable_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'BODEGA', 'EMPLEADO', 'OFICINA', name='rol_usuario_enum'), nullable=False),
    sa.Column('foto_perfil', sa.String(length=200), nullable=True),
    sa.Column('debe_cambiar_contrasena', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('personal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('actas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('abono', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=False),
    sa.Column('numero_documento', sa.String(length=100), nullable=False),
    sa.Column('archivo_soporte', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignacion_diaria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id_proyecto'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('trabajo_manana', sa.Boolean(), nullable=True),
    sa.Column('trabajo_tarde', sa.Boolean(), nullable=True),
    sa.Column('horas_trabajadas', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('nombre_proyecto_eliminado', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('observacion', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiales_proyecto',
    sa.Column('id_mp', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'LISTO', name='estado_material_enum'), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('usado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_material'], ['materiales.id_material'], ),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ),
    sa.PrimaryKeyConstraint('id_mp')
    )
    with op.batch_alter_table('materiales_proyecto', schema=None) as batch_op:
        batch_op.create_index('idx_materiales_proyecto_proyecto_material', ['id_proyecto', 'id_material'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiales_proyecto_id_material'), ['id_material'], unique=False)
        batch_op.create_index(batch_op.f('ix_materiales_proyecto_id_proyecto'), ['id_proyecto'], unique=False)

    op.create_table('proyecto_personal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proyecto_personal', schema=None) as batch_op:
        batch_op.create_index('idx_proyecto_personal_proyecto_personal', ['proyecto_id', 'personal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proyecto_personal_personal_id'), ['personal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proyecto_personal_proyecto_id'), ['proyecto_id'], unique=False)

    op.create_table('proyecto_ubicacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('Planeado', 'En ejecución', 'Finalizado', name='estado_ubicacion_enum'), nullable=False),
    sa.Column('progreso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id_proyecto'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id', 'nombre', name='uix_proyecto_ubicacion_nombre')
    )
    op.create_table('solicitudes_materiales',
    sa.Column('id_solicitud', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_usuario_solicitante', sa.Integer(), nullable=False),
    sa.Column('id_usuario_responsable', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), nullable=True),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'RECHAZADO', name='estado_solicitud_enum'), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_ruta', sa.String(length=255), nullable=True),
    sa.Column('visible_para_bodega', sa.Boolean(), nullable=True),
    sa.Column('nombre_proyecto_eliminado', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ),
    sa.ForeignKeyConstraint(['id_usuario_responsable'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_solicitante'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('documentos_al_dia', sa.Boolean(), nullable=True),
    sa.Column('soat_vencimiento', sa.Date(), nullable=False),
    sa.Column('tecno_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('Disponible', 'En uso', 'Mantenimiento', name='estado_vehiculo_enum'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('proyecto_actual_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_actual', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_actual_id'], ['proyectos.id_proyecto'], ),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('actividades',
    sa.Column('id_actividad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('id_ubicacion', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidades_totales', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['proyecto_ubicacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actividades_id_proyecto'), ['id_proyecto'], unique=False)

    op.create_table('mantenimiento_vehiculo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('proximo', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id_vehiculo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_vehiculo',
    sa.Column('id_movimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('proyecto_anterior_id', sa.Integer(), nullable=True),
    sa.Column('proyecto_nuevo_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_anterior', sa.String(length=100), nullable=True),
    sa.Column('ubicacion_nueva', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proyecto_anterior_id'], ['proyectos.id_proyecto'], ),
    sa.ForeignKeyConstraint(['proyecto_nuevo_id'], ['proyectos.id_proyecto'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario_destino', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('id_horario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_horario'], ['horarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('vehiculo_proyecto',
    sa.Column('id_vp', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_proyecto', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('nombre_proyecto_eliminado', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['proyectos.id_proyecto'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_vp')
    )
    with op.batch_alter_table('vehiculo_proyecto', schema=None) as batch_op:
        batch_op.create_index('idx_vehiculo_proyecto_proyecto_vehiculo', ['id_proyecto', 'id_vehiculo'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_proyecto_id_proyecto'), ['id_proyecto'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_proyecto_id_vehiculo'), ['id_vehiculo'], unique=False)

    op.create_table('avances',
    sa.Column('id_avance', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('unidades_avanzadas', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('trayecto', sa.String(length=100), nullable=True),
    sa.Column('calzada', sa.String(length=100), nullable=True),
    sa.Column('carril', sa.String(length=100), nullable=True),
    sa.Column('ubicacion_pr', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('elemento', sa.String(length=100), nullable=True),
    sa.Column('area_elemento', sa.Float(), nullable=True),
    sa.Column('area_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_actividad'], ['actividades.id_actividad'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_avance')
    )
    op.create_table('avance_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_avance', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('cantidad_usada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_avance'], ['avances.id_avance'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_material'], ['materiales.id_material'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencias',
    sa.Column('id_evidencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_avance', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_avance'], ['avances.id_avance'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidencias')
    op.drop_table('avance_material')
    op.drop_table('avances')
    with op.batch_alter_table('vehiculo_proyecto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculo_proyecto_id_vehiculo'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_proyecto_id_proyecto'))
        batch_op.drop_index('idx_vehiculo_proyecto_proyecto_vehiculo')

    op.drop_table('vehiculo_proyecto')
    op.drop_table('notificaciones')
    op.drop_table('movimiento_vehiculo')
    op.drop_table('mantenimiento_vehiculo')
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actividades_id_proyecto'))

    op.drop_table('actividades')
    op.drop_table('vehiculos')
    op.drop_table('solicitudes_materiales')
    op.drop_table('proyecto_ubicacion')
    with op.batch_alter_table('proyecto_personal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyecto_personal_proyecto_id'))
        batch_op.drop_index(batch_op.f('ix_proyecto_personal_personal_id'))
        batch_op.drop_index('idx_proyecto_personal_proyecto_personal')

    op.drop_table('proyecto_personal')
    with op.batch_alter_table('materiales_proyecto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiales_proyecto_id_proyecto'))
        batch_op.drop_index(batch_op.f('ix_materiales_proyecto_id_material'))
        batch_op.drop_index('idx_materiales_proyecto_proyecto_material')

    op.drop_table('materiales_proyecto')
    op.drop_table('horarios')
    op.drop_table('asistencia')
    op.drop_table('asignacion_diaria')
    op.drop_table('actas')
    op.drop_table('usuarios')
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyectos_responsable_id'))
        batch_op.drop_index(batch_op.f('ix_proyectos_nombre'))
        batch_op.drop_index(batch_op.f('ix_proyectos_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_proyectos_fecha_fin'))
        batch_op.drop_index(batch_op.f('ix_proyectos_estado'))

    op.drop_table('proyectos')
    op.drop_table('historial_materiales')
    op.drop_table('facturas')
    op.drop_table('personal')
    op.drop_table('materiales')
    op.drop_table('cotizaciones')
    # ### end Alembic commands ###
