"""Permitir eliminar personal sin borrar historicos

Revision ID: 97eed943f45b
Revises: c9f24138c379
Create Date: 2026-02-11 06:31:29.839739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97eed943f45b'
down_revision = 'c9f24138c379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.alter_column('personal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('asistencia_personal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'personal', ['personal_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('avances', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('avances_id_usuario_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id_usuario'], ondelete='SET NULL')

    with op.batch_alter_table('proyecto_personal', schema=None) as batch_op:
        batch_op.alter_column('personal_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto_personal', schema=None) as batch_op:
        batch_op.alter_column('personal_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('avances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('avances_id_usuario_fkey'), 'usuarios', ['id_usuario'], ['id_usuario'])
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('asistencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('asistencia_personal_id_fkey'), 'personal', ['personal_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('personal_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
