"""Relacion consignacion con cuenta cobro

Revision ID: 98913d983ec7
Revises: 6932328d5094
Create Date: 2026-02-18 15:40:35.657303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98913d983ec7'
down_revision = '6932328d5094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta_cobro_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'actas', ['cuenta_cobro_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cuenta_cobro_id')

    # ### end Alembic commands ###
