"""Eliminar retenciones de facturas

Revision ID: b080a1b4f3e9
Revises: e338208de38f
Create Date: 2026-02-17 20:28:16.334864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b080a1b4f3e9'
down_revision = 'e338208de38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('reteiva')
        batch_op.drop_column('retefuente')
        batch_op.drop_column('reteica')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reteica', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('retefuente', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reteiva', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
