"""Primera bd

Revision ID: ba6442fadf9a
Revises: 
Create Date: 2025-11-18 08:38:57.025629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6442fadf9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proyecto_actual_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ubicacion_actual', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'proyectos', ['proyecto_actual_id'], ['id_proyecto'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ubicacion_actual')
        batch_op.drop_column('proyecto_actual_id')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
