"""cambio en facturas

Revision ID: c9f24138c379
Revises: 25bcbe573276
Create Date: 2026-02-07 10:02:17.642226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f24138c379'
down_revision = '25bcbe573276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sin_iva', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retencion', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('retencion')
        batch_op.drop_column('total_sin_iva')

    # ### end Alembic commands ###
