"""add belvo link fields

Revision ID: ecafa381425c
Revises: 09ec72562046
Create Date: 2026-06-09 11:56:59.978574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecafa381425c'
down_revision = '09ec72562046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_bancario_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cuenta_externa_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('institucion_externa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('banco_externo_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ultima_sincronizacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('belvo_link_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('belvo_institution', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.drop_column('belvo_institution')
        batch_op.drop_column('belvo_link_id')
        batch_op.drop_column('ultima_sincronizacion')
        batch_op.drop_column('banco_externo_status')
        batch_op.drop_column('institucion_externa')
        batch_op.drop_column('cuenta_externa_id')
        batch_op.drop_column('link_bancario_id')

    # ### end Alembic commands ###
