"""nuevas retenciones en factura

Revision ID: ff89d2197d82
Revises: 42089929ee1a
Create Date: 2026-02-11 11:50:50.651247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff89d2197d82'
down_revision = '42089929ee1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retefuente', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reteiva', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('reteica', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.drop_column('retencion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retencion', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('reteica')
        batch_op.drop_column('reteiva')
        batch_op.drop_column('retefuente')

    # ### end Alembic commands ###
